# Generated by Django 5.0.6 on 2025-10-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='documentacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos_usuarios/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_documentacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('estudiante', 'Estudiante'), ('orientador', 'Orientador'), ('institucion', 'Institución')], default='estudiante', max_length=20),
        ),
    ]
